### ISSUE TITLE
Need for database persistence

### ISSUE THREAD

**Issue by ranisalt** [HeavenIsLost/cast#1]
Are you sure you need the new table to persist data to the database? I feel there is no need for it, the casting stuff could all be done in-memory, and it makes no sense to persist it since it should be flushed every time the server is shut down.

Could we work on it? :P

**Comment by HeavenIsLost** [comment]
Well if you talking about the cast table the purpose of that is to let the acc/website know about casting data. This table is useful if i want to show in my website the current opened casts, how many players they have, if they have password, etc.
